### ISSUE TITLE
Running Hardy from a node_modules folder goes into infinite loop

### ISSUE THREAD

**Issue by dwabyick** [thingsinjars/Hardy#16]
When running Hardy from a project's node_modules folder, hardy goes into an infinite loop. 

To reproduce:

```
mkdir tmp
cd tmp
npm install hardy
./node_modules/hardy/bin/hardy init
./node_modules/hardy/bin/hardy .
```

Output is:
Hardy v1.0.1
Using external selenium.
CSS Utils Steps Loaded
CSS Steps Loaded
Generic Steps Loaded
Loading browser firefox
.FShutting down browser
Loading browser firefox
.FShutting down browser
Loading browser firefox
...Shutting down browser
Loading browser firefox
.F-Shutting down browser
Loading browser firefox
..Shutting down browser
Loading browser firefox
.FShutting down browser
Loading browser firefox

Granted, the instructions _do_ say to install it globally ... ;-)

**Comment by thingsinjars** [comment]
I'll admit, I've never tried it that way. Lets pretend it's a feature. A recursive feature. 

Actually, I don't run it globally on my dev machine so it should be fine without that. Are you sure it's in an infinite loop? The output above isn't actually repeating, there are different numbers of tests. 

That said, it probably would loop if you ran it from a folder which was a parent of the hardy folder as it'll recurse down until it finds hardy then spin up a new test world and start again from the root. That sounds like what's happening.
