### ISSUE TITLE
Process for cross-platform screenshots

### ISSUE THREAD

**Issue by thingsinjars** [thingsinjars/Hardy#4]
When integrating Hardy into a build-pipeline, the environment where reference image diffs are taken is usually not the same one the comparison images are created.

Hardy should be platform aware and generate new reference cases if no references exist for this platform.

For example:
1. I create an image diff test on my mac
2. I create reference files locally then run the tests
3. I will use these reference renders as my base case so I commit them
4. I push to remote VCS
5. Linux-based CI server picks up the change
6. CI builds project, runs tests
7. Runs image diff test
8. Images are different due to platform differences.
9. Test fails

If Hardy were platform-aware, this would simply result in new reference images being created the same as a typical first-run image diff test.

**Comment by thingsinjars** [comment]
Screenshots are now named with the platform as well:

For example: `darwin_firefox_body_0.png`

**Comment by CaptainQuirk** [comment]
Hi, 

Quick questions : 
- do you think it could be interesting to have the browser version in the filename ? 
- Couldn't a folder structure be of advantage in comparison with tokens separated by underscores ?

Thx for your work

**Comment by thingsinjars** [comment]
Both good suggestions. I'd be a little worried that the first would create tests that didn't compare older tests against newer versions of the browser as they came out so there may be unexpected differences that you don't get alerted about.

Anybody else got thoughts on versions in the diffs?
