### ISSUE TITLE
Unknown system error when running first test

### ISSUE THREAD

**Issue by rjonesie** [thingsinjars/Hardy#5]
I'm following your First Test example from http://hardy.io/getting-started.html.
I'm running it on a 64-bit Win 7 box.
I've performed all prereq steps successfully, but when I run the executable command, I get an unknown system error:

$ hardy .
Hardy v0.0.10

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn Unknown system errno 193
    at errnoException (child_process.js:975:11)
    at Process.ChildProcess._handle.onexit (child_process.js:766:34)

I'm not sure if this is an issue with my environment, or something else.  I noticed I don't have hardy or phantomjs in my Path (your instructions during install say a hardy executable will be placed in my path).  However, when I manually add it to my path, it makes no difference.  Is this something you're familiar with or maybe have a suggested workaround or fix? 

Thanks!

**Comment by thingsinjars** [comment]
Urk. I don't actually have a quick fix. The main reason I haven't really 'launched' hardy yet is that I haven't had a chance to play with it much on Windows (any flavour) or try and break it. I'm hoping to get a chance over the next week.

So far my testing has been limited to Linux and OS X.

**Comment by rjonesie** [comment]
No worries.  I know I'm waaay early.  I'm really excited at what you're trying to accomplish with this & can't wait to pick it up.  Maybe I'll go play with Ghost Story in the meantime.  I'll keep an eye out here, though!  Thanks for the reply.

**Comment by thingsinjars** [comment]
I think the initial issue may be fixed. Windows doesn't like the way I was spawning the child processes so I've moved to using [win-spawn](https://github.com/ForbesLindesay/win-spawn) instead. 

The latest version pushed to npm (v0.0.11) should, in theory, work. Or at least, not crash. Probably.

**Comment by rjonesie** [comment]
Definitely an improvement!  Thanks a bunch for taking time to fix it.  I'm also installing on OSx just for the heck of it.  Good stuff, thanks again.

**Comment by thingsinjars** [comment]
Cool. Let me know how it goes.
