### ISSUE TITLE
hardy can't find page elements

### ISSUE THREAD

**Issue by rjonesie** [thingsinjars/Hardy#6]
I'm using this page structure for my test:

```
<div class="container">
  <div class="page-header">
  <div class="row ui-sortable">
    <section class="module span4 actionable draggable scrollable">
      <header class="module-header">
      <div class="module-body">
        <div>
    <ul class="message-list">
      <li class="message-item">
        <a href="#">
          <span class="label label-important pull-left">Urgent</span><h4
```

Previously in .10 and early in .11, my tests were running successfully with this assertion:
Then "module-body" should have "color" of "#313337"

However, that assertion now generates this error:
NoSuchElement: An element could not be located on the page using the given search parameters.:   "module-body"

I've tried using "div class = module-body", "section class = module span4 actionable draggable scrollable", "<section class="module span4 actionable draggable scrollable">", and other various combinations that either result in a similar error or a server error.  Do I need to write the tests differently in my feature files to account for a recent change/update, or is this a bug?  Thanks!

**Comment by thingsinjars** [comment]
Nothing has changed with the element finding recently so it should still work. 

Could you share your `selectors.js` file? Maybe there's something in that.

You could also try directly referencing the element using 

```
Then ".module-body" should have "color" of "#313337"
```

_Note the '.' class selector at the beginning._

This should try and use that selector directly instead of using a reference from the `selectors.js`

**Comment by rjonesie** [comment]
Perfect!  I wasn't aware of the ability to bypass selector.js.  Adding '.' took care of it.  Thanks so much for your lightening fast response. :-)

**Comment by thingsinjars** [comment]
No problem. :)
