### ISSUE TITLE
Using :contains() pseudo class selector

### ISSUE THREAD

**Issue by jessecravens** [thingsinjars/Hardy#7]
Is it possible to use the :contains() pseudo class selector to assert text() values?

**Comment by thingsinjars** [comment]
The CSS selectors are passed through to Selenium so it should work ([according to this](http://sauceio.com/index.php/2010/03/selenium-tips-finding-elements-by-their-inner-text-using-contains-a-css-pseudo-class/)) but I haven't tried it yet.

If not, it is definitely possible to write a step in the `step_definitions` folder to use Selenium directly. There's more info about that [on the site](http://hardy.io/custom-steps.html).

**Comment by rjonesie** [comment]
I've tried using "contains() a few different ways in my feature file:

And ".panel-body" should "h3:contains()" "About Us"
And ".panel-body > h3" should ":contains()" "About Us"
And "div > panel-body" should "h3:contains()" "About Us"

These resulted in:
1 scenario (1 undefined)
7 steps (1 undefined, 6 passed)

You can implement step definitions for undefined steps with these snippets:

this.Then(/^"([^"]_)" should "([^"]_)" "([^"]*)"$/, function(arg1, arg2, arg3, callback) {
  // express the regexp above with the code you wish you had
  callback.pending();
});

I also used TextContent, InnerHTML, InnerText, and OuterText, but Hardy sees these as undefined:

And "panel body" should have ":textContent()" of "About Us"

I got this back:
(::) failed steps (::)

"panel body" should have :textContent() of About Us, measured:

I tried the Chrome extension too but it doesn't recognize any of these properties either.  It has to be a style element.

Is custom JS required to get around this?

**Comment by rjonesie** [comment]
Thought maybe it needed to be a "p", so I tried this, too, but it didn't work:
(::) failed steps (::)

".panel-body > h3" should have p:first-child of At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti., measured:

**Comment by thingsinjars** [comment]
So, it seems that Selenium Webdriver [doesn't support :contains pseudo-selectors](http://stackoverflow.com/questions/16374667/does-selenium-webdriver-support-css-contains). It would be possible to select this way based on XPath but there isn't a clean way at the moment to pass XPath through Hardy to Selenium WebDriver while bypassing WebDriverJS (which only uses CSS Selectors).

@rjonesie Your step appears to be a bit off there. _If_ contains would have worked, the step would have been:

```
And ".panel-body > h3:contains('About Us')" should have "<css-property>" of "<value>"
```

But, as I said, it doesn't work, anyway. If there's a nice way to use XPath, I'll see about including it alongside CSS selectors but I worry that might confuse things.
